### ISSUE TITLE
ERT channels are one day behind

### ISSUE THREAD

**Issue by noworthwhile** [chrisliatas/greek-xmltv#8]
ERT channels are one day behind.

Today February 15th shows programs from February 14th.

**Comment by chrisliatas** [comment]
Hi,
Thanks for catching that. I believe ERT must have changed the time they update their tv-guides. I re-scheduled to grub the guides a bit later. Let's see if this fixes it.

**Comment by chrisliatas** [comment]
It is definitely, an issue associated with the time ERT updates their on-line tv-guides (https://program.ert.gr/Ert1/, etc.). Currently data was grubbed before 06:00 EET, as both ERT and Digea were updating their guides around (or before) 05:30 EET. ERT must have changed this. I will re-schedule grubbing at an event later time after 06:00 EET for tomorrow, hopefully this catch the updates.

**Comment by chrisliatas** [comment]
Today's Release 2021.2.17 looks good, so I will close this.
