### ISSUE TITLE
Action doesn’t generate the files

### ISSUE THREAD

**Issue by sioakim** [chrisliatas/greek-xmltv#82]
The generated xml files seem be to empty for the last 4-5 days

**Comment by chrisliatas** [comment]
Thanks, for pointing the empty files issue. Digea.gr changed their website structure recently, so the grubber cannot grub the necessary info to create the files. I will try to update the scripts, but don't have much capacity at the moment, so can't really tell when this will happen. For the time being, I'm pausing the daily xmltv files releases.
